### PR TITLE
Create Root.py

### PR DESCRIPTION
**Pull request by ghost**
Hello , I've created a simple python program to find the nature of the roots of the quadratic equation . Hope it is ok . All the best and I hope y'all too will enjoy Open Sourcing .

### CODE REVIEW

**Comment by Easyvipin** [comment]
please send the pr again with only one commit as it also contains the previous commits.

**Comment by ghost** [comment]
ok , sure will do

**Comment by ghost** [comment]
@Easyvipin  Hey , how do I delete commits ?

**Comment by Easyvipin** [comment]
https://gist.github.com/CrookedNumber/8964442

**Comment by ghost** [comment]
hey , I've been trying to delete the commits but it's not working , could you please help .

**Pull request closed without merging**
